### ISSUE TITLE
500 error on logging in

### ISSUE THREAD

**Issue by djvarnau** [dxprog/anime-bracket#19] opened 2018-05-31 19:07 UTC
I'm trying to log in through reddit, but I just get a 500 error when I click the allow button

**Comment by dxprog** [comment] 2018-05-31 22:22
Would you mind PMing me your username? (u/mhackmann on reddit) Will make it easier for me to see what's up as I was unable to repro.

**Comment by djvarnau** [comment] 2018-05-31 23:10
Message sent!

**Comment by dxprog** [comment] 2018-06-01 14:56
Error logs and verification with djvarnau suggests that the issue is fixed. Closing.

**Closed by dxprog** 2018-06-01 14:56 UTC
