### ISSUE TITLE
[Enhancement]Support additional media types in character view

### ISSUE THREAD

**Issue by RouganStriker** [dxprog/anime-bracket#6] opened 2015-05-11 17:22 UTC
Notably videos; if a link to a video is specified in the "Link to Picture" field on the nomination form, on the corresponding character view, use that link to generate an embedded video player (works for youtube, vimeo, etc links). A button will take the place of where an image would be displayed and its function is to hide/show the embedded video player; similar to how videos are displayed inline by the [Reddit Enhancement Suite](https://github.com/honestbleeps/Reddit-Enhancement-Suite/tree/5a2637ab9dee70eb0235b12f59f3431d9ef85261/lib/modules/hosts).

**Comment by dxprog** [comment] 2015-05-11 23:55
Detecting URLs and linking to them I can do, but I don't think I've got the time to put into an embedded player, especially for multiple services.

**Comment by RouganStriker** [comment] 2015-05-13 15:59
That's fine, I can look into the latter if you also think this would be a worthwhile enhancement to make.

**Comment by chiefnoah** [comment] 2015-05-13 16:30
What about having the video in in overlay? It could be easier to implement(?) and wouldn't displace the rest of the markup.

**Comment by dxprog** [comment] 2015-05-13 18:15
Yeah, overlay vs inline is less the problem. If this is supposed to replace the image field, we'd need to call APIs to these services to retrieve thumbnails of the video. Also, would probably need a field or some way to identify an item as being a video (maybe the source field is disabled and the link stored there). Ideally, there'd be a scalable system built around that so more services could be added in the future. Any way you spin it, doing it correctly is a non-trivial amount of work (arguably, a lot of things need to be refactored in general...).

The short term solution is to allow links in the source field and link out when one is detected.

**Comment by chiefnoah** [comment] 2015-05-13 18:34
I probably shouldn't do this stuff when I'm supposed to be paying attention in class... I didn't even think about the actual work that would have to go into it to make it work

**Comment by dxprog** [comment] 2015-05-13 19:49
Heh. I've just been in the industry so long, I'm automatically figuring out everything that must be done and any way of convincing project managers to either give more time or scale back ;)

**Comment by dxprog** [comment] 2020-07-20 18:26
Closing as dupe of #27 (which is in progress)

**Closed by dxprog** 2020-07-20 18:26 UTC
